name: Python CD - Local Deployment

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy app locally
        run: |
          cd /home/david/testcicd
          git pull origin main
          source /home/david/testcicd/venv/bin/activate
          pip install -r requirements.txt
          systemctl restart your-python-app.service
